install:
- wget "https://raw.githubusercontent.com/globalbioticinteractions/globinizer/master/check-dataset.sh" -O check-dataset.sh
- chmod +x check-dataset.sh
- wget "https://raw.githubusercontent.com/globalbioticinteractions/globinizer/master/resolve-names.sh" -O resolve-names.sh
- chmod +x resolve-names.sh
- wget "https://raw.githubusercontent.com/globalbioticinteractions/globinizer/master/create-taxon-cache-map.sh" -O create-taxon-cache-map.sh
script: "./resolve-names.sh ${TRAVIS_REPO_SLUG}"
env:
  global:
  - secure: ZowcIZEK7xKoJ/GMLmhuJIztm6442KMlQBFoxEiBL9sX1fxp72gRk9bBTpKhfN4fK/lPhr+gukjkVykCNFFUZliRhOXZNPEdSsb9JUNoIvL9O7/4aW5onMOGrjvOYKaljgBdR1NMCYlLXKiQ6KQu9HkgTv74Lvc9QqzkYXEpdN8=
  - secure: DO2ZjFrN2XuNIFoN4GjfdLkS8ZIh1sGL8KgWIZWjZjuoX1PIL18eS3tjSBL4XUcZyLaTTeBWCbHnRF6Z+/MqHwx/BL//tum+F13Lzv7CeSBsmV75TAWDvziAYMQDtmKqKjjS5vdlG6rNPxnuHTCzrGkUoEyacUrSmz1B7/+2L0A=
  - secure: RUYrsxI2MAahG1UAx/JdNezEKcXUXEP6Qhur3Ki34UVid8Z6GfDduJwEewF4LsfI5zg1zlRjkDhoWYixF0nQ6D10KhVOWu3cyKVTD6Pnx1W8ZzulYQ9eA+zpwhEgGeGlb36ezy0QYbDuBNB38K2XRgbwqXYn1ugcV7wzgae16Mc=
